library(shiny)
library(shinythemes)
library(shinydashboard)
library(shinycssloaders)
library(shinyWidgets)
library(shinyjs)
library(shinyBS)
library(DT)
library(ggplot2)
library(ggiraph)
library(plotly)
library(stringr)
library(lubridate)
library(tidyverse)
library(reshape2)
library(openxlsx)
library(DBI)

options(spinner.color = "#7197A4", spinner.color.background = "#ffffff", spinner.size = 2, shiny.reactlog=TRUE)


source("sidebar.R")
source("header.R")
source("page.R")
source("fun_shinyInput.R")
source("ui.R")
source("server.R")


shinyApp(ui, server)
